/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLink: typeof import('./components/AppLink.vue')['default']
    AppLoader: typeof import('./components/AppLoader.vue')['default']
    CalendarCard: typeof import('./components/CalendarCard.vue')['default']
    CalendarDays: typeof import('./components/CalendarDays.vue')['default']
    CookingInstructions: typeof import('./components/CookingInstructions.vue')['default']
    HelloWorld: (typeof import("./src/components/HelloWorld.vue"))["default"]
    MealPlanner: typeof import('./components/MealPlanner.vue')['default']
    RecipeRating: typeof import('./components/RecipeRating.vue')['default']
    RecipeSearch: typeof import('./components/RecipeSearch.vue')['default']
    RecipesList: typeof import('./components/RecipesList.vue')['default']
    RecipeTable: typeof import('./components/RecipeTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
